### ISSUE TITLE
Project active?

### ISSUE THREAD

**Issue by stickystyle** [bdurrer/home-assistant-blockly#1]
I was wondering if you’re still playing with this idea or if you stopped, did you hit a roadblock? I was going to try doing this myself, but didn’t want to hit a dead end.

**Comment by bdurrer** [comment]
The blockly GUI is finished and it can generate an valid configuration. The reading of an config is pretty much inexistent, but it don't see any blockers there.

The reason that I stopped was that there already is a wysiwyg editor  in HA now.

I think the state on the repo here is not my most recent one. I'll validate it in the next days.
But anyway, feel free to fork or take over, if you like! I won't continue the project

**Comment by bdurrer** [comment]
I updated the readme and fixed the configuration. If you have any questions, just ask.
Have fun with it! and let me know when you actually manage to create a HA component  :simple_smile:

**Comment by stickystyle** [comment]
Cool, thanks!
