### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by simonckenyon** [bdurrer/home-assistant-blockly#3]
could you perhaps explain how this is used.
i have used blockly in an application - so i know what it is and how it works.
but is this designed to integrate into ha or is it a separate application that just spits out yalm?

**Comment by bdurrer** [comment]
It is only a single page where you can edit yaml configurations.
Since HA got it's own WYSIWYG configuration editor, I stopped working on it. So no, it's not integrated at all.
Maybe contact stickystyle (see #1 ), he wanted to implement something himself.
