### ISSUE TITLE
load/save configuration

### ISSUE THREAD

**Issue by simonckenyon** [bdurrer/home-assistant-blockly#4]
you say that there are no blockers. could you point me where in the code (if any).

**Comment by bdurrer** [comment]
Sorry, I don't understand what your question is. Where did I say what about what?

**Comment by simonckenyon** [comment]
you say in #1 "The blockly GUI is finished and it can generate an valid configuration. The reading of an config is pretty much inexistent, but it don't see any blockers there."

i was wondering if you had done any work on this?
the blockly block factory has a mechanism which maybe could be used.

**Comment by bdurrer** [comment]
Ah! In that context, blockers=problems :-)
And yes, if I were to do it, I would use the block factory on top of the
rest service that was introduced with the wysiwyg editor of HA

Am 20.02.2018 18:27 schrieb "Simon Kenyon" <notifications@github.com>:
