### ISSUE TITLE
Better documentation for a noob

### ISSUE THREAD

**Issue by pizzulicchio** [bdurrer/home-assistant-blockly#6]
Hi,
i have unzipped the content into my home assistant root ( /usr/share/hassio/homeassistant ) creating the new folder named, as suggested, "blockly".
What is needed to do to "make appear" into the gui of homeassistant the blockly section ?

**Comment by bdurrer** [comment]
It won't appear in HA, this is just an implementation that can read (and generate) elements of the HA configuration scheme. it's not integrated at all. However, it can be run independently of HA. You would need tools `npm` (or `yarn`) to load the dependencies and `node` (`gulp` is installed as dependency automatically by npm/yarn) to run it.
